[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "flask>=3.1.0",
    "pdfkit>=1.0.0",
    "plotly>=6.0.1",
    "psycopg2-binary>=2.9.10",
]
